"""`study` CLI: run | simulate | estimate | report | graph."""

from __future__ import annotations

import asyncio
import logging
from pathlib import Path
from typing import Annotated

import typer
from dotenv import load_dotenv

app = typer.Typer(no_args_is_help=True, add_completion=False)
Config = Annotated[Path, typer.Option("--config", "-c", exists=True, dir_okay=False,
                                      help="config/experiments/eN_*.yaml")]


@app.callback()
def _setup() -> None:
    # Langfuse's get_client() reads the process env only; Settings reads .env itself.
    load_dotenv(".env")
    from routing_study.tracing.langfuse import init

    init()
    logging.basicConfig(level=logging.WARNING, format="%(levelname)s %(name)s: %(message)s")


@app.command()
def run(
    config: Config,
    split: Annotated[str, typer.Option(help="dev | test")] = "dev",
    mode: Annotated[str, typer.Option(help="e2e | routing-only")] = "e2e",
    limit: Annotated[int | None, typer.Option(help="first N cases (interleaved by category)")]
    = None,
    reps: Annotated[int, typer.Option(min=1)] = 1,
    concurrency: Annotated[int, typer.Option(min=1)] = 4,
    run_name: Annotated[str | None, typer.Option(help="Langfuse dataset run name")] = None,
    routing_mode: Annotated[str | None, typer.Option(
        help="override routing.mode (single|cascade|shadow)")] = None,
) -> None:
    """Run one experiment config over a split; writes results/<run_name>.jsonl."""
    from routing_study.eval.report import render
    from routing_study.eval.runner import Runner, default_run_name, load_cases
    from routing_study.settings import load_settings

    if mode not in ("e2e", "routing-only"):
        raise typer.BadParameter("mode must be e2e or routing-only")
    settings = load_settings(config)
    if routing_mode:
        settings.routing.mode = routing_mode  # type: ignore[assignment]
    name = run_name or default_run_name(settings.experiment_id, split, mode)
    cases = load_cases(split, limit)
    runner = Runner(settings, split=split, mode=mode, run_name=name,  # type: ignore[arg-type]
                    reps=reps, concurrency=concurrency)
    out = asyncio.run(runner.run(cases))
    typer.echo(f"run {name}: {len(cases)} cases x {reps} reps -> {out}")
    typer.echo(render([out]))


@app.command()
def report(
    files: Annotated[list[Path] | None, typer.Argument(help="results/*.jsonl (default: all)")]
    = None,
) -> None:
    """Accuracy / cost / latency per run from the local results files."""
    from routing_study.eval.report import render

    paths = files or sorted(Path("results").glob("*.jsonl"))
    typer.echo(render(paths))


@app.command()
def simulate(
    results: Annotated[Path, typer.Argument(exists=True, help="results of a shadow run")],
    config: Config,
) -> None:
    """Replay a config's cascade offline over the shadow decisions of a results file."""
    from routing_study.eval.simulate import render_simulation
    from routing_study.settings import load_settings

    typer.echo(render_simulation(results, load_settings(config)))


@app.command()
def estimate(
    config: Config,
    split: str = "test",
    mode: str = "e2e",
    reps: int = 3,
    limit: int | None = None,
) -> None:
    """Cost estimate for a run, before spending."""
    from routing_study.eval.estimate import estimate as do_estimate
    from routing_study.eval.runner import load_cases
    from routing_study.settings import load_settings

    settings = load_settings(config)
    typer.echo(asyncio.run(do_estimate(settings, len(load_cases(split, limit)), reps, mode)))


@app.command()
def graph(out: Path = Path("docs/graph.md")) -> None:
    """Write the LangGraph topology as a mermaid diagram."""
    from routing_study.graph.builder import build_graph

    mermaid = build_graph().get_graph().draw_mermaid()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "# Host graph\n\nGenerated by `uv run study graph`. Routing-only runs compile the same "
        "graph with `interrupt_before=[\"agent\"]`; E0 (native) passes through `route_skill` "
        "and `route_tool`.\n\n```mermaid\n" + mermaid + "```\n", encoding="utf-8")
    typer.echo(f"wrote {out}")


@app.command()
def trace(trace_id: str) -> None:
    """Print one trace's observation tree and scores from the Langfuse API."""
    from routing_study.tracing.langfuse import LangfuseAPI, format_tree

    api = LangfuseAPI()
    obs, scores = api.wait(trace_id, timeout_s=10)
    typer.echo(format_tree(obs))
    typer.echo("scores: " + ", ".join(f"{s['name']}={s.get('value', s.get('stringValue'))}"
                                      for s in scores))


if __name__ == "__main__":
    app()
